### ISSUE TITLE
Reproduction failed

### ISSUE THREAD

**Issue by kun-dao** [yxgeee/OpenIBL#9]
I used the script `./scripts/train_sfrs_dist.sh` to train SFRS on 4 GPUs(satisfy~11G per GPU) but failed to reproduce the results. Here are our reproduction result details ：

  |   | Pitts250k |   |   | Tokyo24/7 |  
-- | -- | -- | -- | -- | -- | --
  | recall@1 | recall@5 | recall@10 | recall@1 | recall@5 | recall@10
paper | 90.7 | 96.4 | 97.6 | 85.4 | 91.1 | 93.3
run1 | 90.0 | 95.8 | 97.0 | 81.0 | 89.5 | 91.1
run2 | 89.9 | 95.8 | 97.0 | 79.0 | 88.9 | 89.8

Can you give us any advice on this situation？

**Comment by yxgeee** [comment]
Hopefully, "model_best.pth" selected in training according to its performance on pitts30k_val could show good generalization ability on tokyo dataset. But unfortunately, due to the training randomness, sometimes "model_best.pth" only performs well on pitts but shows inferior performance on tokyo. So in practice, I recommend to test all the five checkpoints in the last generation, and generally at least one of them would achieve satisfactory performance on tokyo.
